#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum RelicRarity {
    Ancient,
    Common,
    Event,
    None,
    Starter,
    Shop,
    Rare,
    Uncommon,
}



#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Relic {
    DistinguishedCape,
    LuckyFysh,
    Nunchaku,
    OrnamentalFan,
    Whetstone,
    PumpkinCandle,
    SneckoSkull,
    DustyTome,
    MeatOnTheBone,
    SwordOfStone,
    EmotionChip,
    BurningBlood,
    StoneHumidifier,
    RingOfTheSnake,
    RunicPyramid,
    TheAbacus,
    Glitter,
    LordsParasol,
    ChoicesParadox,
    LostWisp,
    Girya,
    DivineDestiny,
    WongosMysteryTicket,
    MiniatureCannon,
    JossPaper,
    IronClub,
    ParryingShield,
    Pear,
    PrayerWheel,
    Lantern,
    LavaLamp,
    LoomingFruit,
    SelfFormingClay,
    ArtOfWar,
    EternalFeather,
    HelicalDart,
    PreciseScissors,
    RadiantPearl,
    FakeStrikeDummy,
    HistoryCourse,
    MassiveScroll,
    EmptyCage,
    PaelsBlood,
    MealTicket,
    MusicBox,
    PaelsLegion,
    ScreamingFlagon,
    FrozenEgg,
    BoundPhylactery,
    ElectricShrymp,
    Fiddle,
    RuinedHelmet,
    WongoCustomerAppreciationBadge,
    Circlet,
    NewLeaf,
    OldCoin,
    PrismaticGem,
    RazorTooth,
    MoltenEgg,
    WhiteStar,
    FakeSneckoEye,
    PaelsTooth,
    HappyFlower,
    WingCharm,
    ForgottenSoul,
    PaelsFlesh,
    BronzeScales,
    PrecariousShears,
    JewelryBox,
    MummifiedHand,
    StrikeDummy,
    SandCastle,
    PunchDagger,
    WarHammer,
    Orichalcum,
    FragrantMushroom,
    BloodSoakedRose,
    RegalPillow,
    ScrollBoxes,
    YummyCookie,
    BeatingRemnant,
    BowlerHat,
    CentennialPuzzle,
    DataDisk,
    RingingTriangle,
    ThrowingAxe,
    Storybook,
    FuneraryMask,
    DeprecatedRelic,
    Pocketwatch,
    FurCoat,
    PotionBelt,
    NinjaScroll,
    LeafyPoultice,
    HornCleat,
    DollysMirror,
    FakeHappyFlower,
    Planisphere,
    PaelsEye,
    NutritiousOyster,
    DreamCatcher,
    RedSkull,
    ToughBandages,
    RoyalPoison,
    NutritiousSoup,
    TanxsWhistle,
    IntimidatingHelmet,
    BiiigHug,
    OddlySmoothStone,
    PaelsHorn,
    SymbioticVirus,
    LeadPaperweight,
    LizardTail,
    PenNib,
    PollinousCore,
    Driftwood,
    Permafrost,
    FresnelLens,
    MrStruggles,
    PreservedFog,
    DarkstonePeriapt,
    Sozu,
    SereTalon,
    TungstenRod,
    MembershipCard,
    LeesWaffle,
    VeryHotCocoa,
    BeautifulBracelet,
    BoneFlute,
    FakeLeesWaffle,
    BlackBlood,
    PaelsWing,
    VexingPuzzlebox,
    BoomingConch,
    FakeVenerableTeaSet,
    GoldenCompass,
    Mango,
    PetrifiedToad,
    GamePiece,
    Kunai,
    Bread,
    MysticLighter,
    BookOfFiveRings,
    AmethystAubergine,
    Shovel,
    GnarledHammer,
    MiniRegent,
    VenerableTeaSet,
    SilverCrucible,
    GremlinHorn,
    RainbowRing,
    WhisperingEarring,
    Chandelier,
    SmallCapsule,
    SignetRing,
    TuningFork,
    Crossbow,
    Gorget,
    DiamondDiadem,
    AlchemicalCoffer,
    MawBank,
    Vajra,
    TouchOfOrobas,
    GoldenPearl,
    PowerCell,
    CrackedCore,
    SeaGlass,
    Pendulum,
    DaughterOfTheWind,
    VelvetChoker,
    Orrery,
    Kifuda,
    Regalite,
    DivineRight,
    UndyingSigil,
    DelicateFrond,
    FakeAnchor,
    Metronome,
    MercuryHourglass,
    SparklingRouge,
    Candelabra,
    LunarPastry,
    CharonsAshes,
    FakeMerchantsRug,
    PandorasBox,
    Akabeko,
    Shuriken,
    PaelsTears,
    CursedPearl,
    DingyRug,
    GalacticDust,
    LostCoffer,
    ArchaicTooth,
    GoldPlatedCables,
    TheBoot,
    RedMask,
    FestivePopper,
    LargeCapsule,
    BlessedAntler,
    SealOfGold,
    ToastyMittens,
    UnceasingTop,
    UnsettlingLamp,
    WhiteBeastStatue,
    IvoryTile,
    RingOfTheDrake,
    Pantograph,
    PhilosophersStone,
    SlingOfCourage,
    Claws,
    ReptileTrinket,
    BingBong,
    Byrdpip,
    SpikedGauntlets,
    BigHat,
    PhylacteryUnbound,
    EmberTea,
    SwordOfJade,
    GamblingChip,
    Kusarigama,
    SturdyClamp,
    TheCourier,
    TinyMailbox,
    PaelsClaw,
    BurningSticks,
    PaperKrane,
    FakeMango,
    TriBoomerang,
    CaptainsWheel,
    JuzuBracelet,
    MeatCleaver,
    FakeOrichalcum,
    ArcaneScroll,
    StoneCalendar,
    FakeBloodVial,
    RunicCapacitor,
    VitruvianMinion,
    BlackStar,
    ChosenCheese,
    MiniatureTent,
    Strawberry,
    BoneTea,
    BookRepairKnife,
    ChemicalX,
    GlassEye,
    CloakClasp,
    DragonFruit,
    LetterOpener,
    Toolbox,
    JeweledMask,
    Anchor,
    BagOfMarbles,
    Cauldron,
    LavaRock,
    BeltBuckle,
    Sai,
    TwistedFunnel,
    WarPaint,
    SneckoEye,
    Astrolabe,
    Bellows,
    LastingCandy,
    Ectoplasm,
    NeowsTorment,
    IceCream,
    OrangeDough,
    Pomander,
    Tingsha,
    BigMushroom,
    BloodVial,
    BrilliantScarf,
    HandDrill,
    ToyBox,
    BagOfPreparation,
    PaperPhrog,
    GhostSeed,
    StoneCracker,
    Bookmark,
    TeaOfDiscourtesy,
    CallingBell,
    DemonTongue,
    FencingManual,
    InfusedCore,
    RippleBasin,
    PaelsGrowth,
    Brimstone,
    RoyalStamp,
    Vambrace,
    ToxicEgg,
}

impl Relic {
    pub fn rarity(&self) -> RelicRarity {
        match self {
            Relic::Akabeko => RelicRarity::Uncommon,
            Relic::AlchemicalCoffer => RelicRarity::Ancient,
            Relic::AmethystAubergine => RelicRarity::Common,
            Relic::Anchor => RelicRarity::Common,
            Relic::ArcaneScroll => RelicRarity::Ancient,
            Relic::ArchaicTooth => RelicRarity::Ancient,
            Relic::ArtOfWar => RelicRarity::Rare,
            Relic::Astrolabe => RelicRarity::Ancient,
            Relic::BagOfMarbles => RelicRarity::Uncommon,
            Relic::BagOfPreparation => RelicRarity::Common,
            Relic::BeatingRemnant => RelicRarity::Rare,
            Relic::BeautifulBracelet => RelicRarity::Ancient,
            Relic::Bellows => RelicRarity::Uncommon,
            Relic::BeltBuckle => RelicRarity::Shop,
            Relic::BigHat => RelicRarity::Rare,
            Relic::BigMushroom => RelicRarity::Event,
            Relic::BiiigHug => RelicRarity::Ancient,
            Relic::BingBong => RelicRarity::Event,
            Relic::BlackBlood => RelicRarity::Starter,
            Relic::BlackStar => RelicRarity::Ancient,
            Relic::BlessedAntler => RelicRarity::Ancient,
            Relic::BloodSoakedRose => RelicRarity::Ancient,
            Relic::BloodVial => RelicRarity::Common,
            Relic::BoneFlute => RelicRarity::Common,
            Relic::BoneTea => RelicRarity::Event,
            Relic::Bookmark => RelicRarity::Rare,
            Relic::BookOfFiveRings => RelicRarity::Common,
            Relic::BookRepairKnife => RelicRarity::Uncommon,
            Relic::BoomingConch => RelicRarity::Ancient,
            Relic::BoundPhylactery => RelicRarity::Starter,
            Relic::BowlerHat => RelicRarity::Uncommon,
            Relic::Bread => RelicRarity::Shop,
            Relic::BrilliantScarf => RelicRarity::Ancient,
            Relic::Brimstone => RelicRarity::Shop,
            Relic::BronzeScales => RelicRarity::Common,
            Relic::BurningBlood => RelicRarity::Starter,
            Relic::BurningSticks => RelicRarity::Shop,
            Relic::Byrdpip => RelicRarity::Event,
            Relic::CallingBell => RelicRarity::Ancient,
            Relic::Candelabra => RelicRarity::Uncommon,
            Relic::CaptainsWheel => RelicRarity::Rare,
            Relic::Cauldron => RelicRarity::Shop,
            Relic::CentennialPuzzle => RelicRarity::Common,
            Relic::Chandelier => RelicRarity::Rare,
            Relic::CharonsAshes => RelicRarity::Rare,
            Relic::ChemicalX => RelicRarity::Shop,
            Relic::ChoicesParadox => RelicRarity::Ancient,
            Relic::ChosenCheese => RelicRarity::Event,
            Relic::Circlet => RelicRarity::None,
            Relic::Claws => RelicRarity::Ancient,
            Relic::CloakClasp => RelicRarity::Rare,
            Relic::CrackedCore => RelicRarity::Starter,
            Relic::Crossbow => RelicRarity::Ancient,
            Relic::CursedPearl => RelicRarity::Ancient,
            Relic::DarkstonePeriapt => RelicRarity::Event,
            Relic::DataDisk => RelicRarity::Common,
            Relic::DaughterOfTheWind => RelicRarity::Event,
            Relic::DelicateFrond => RelicRarity::Ancient,
            Relic::DemonTongue => RelicRarity::Rare,
            Relic::DeprecatedRelic => RelicRarity::None,
            Relic::DiamondDiadem => RelicRarity::Ancient,
            Relic::DingyRug => RelicRarity::Shop,
            Relic::DistinguishedCape => RelicRarity::Ancient,
            Relic::DivineDestiny => RelicRarity::Starter,
            Relic::DivineRight => RelicRarity::Starter,
            Relic::DollysMirror => RelicRarity::Shop,
            Relic::DragonFruit => RelicRarity::Shop,
            Relic::DreamCatcher => RelicRarity::Event,
            Relic::Driftwood => RelicRarity::Ancient,
            Relic::DustyTome => RelicRarity::Ancient,
            Relic::Ectoplasm => RelicRarity::Ancient,
            Relic::ElectricShrymp => RelicRarity::Ancient,
            Relic::EmberTea => RelicRarity::Event,
            Relic::EmotionChip => RelicRarity::Rare,
            Relic::EmptyCage => RelicRarity::Ancient,
            Relic::EternalFeather => RelicRarity::Uncommon,
            Relic::FakeAnchor => RelicRarity::Event,
            Relic::FakeBloodVial => RelicRarity::Event,
            Relic::FakeHappyFlower => RelicRarity::Event,
            Relic::FakeLeesWaffle => RelicRarity::Event,
            Relic::FakeMango => RelicRarity::Event,
            Relic::FakeMerchantsRug => RelicRarity::Event,
            Relic::FakeOrichalcum => RelicRarity::Event,
            Relic::FakeSneckoEye => RelicRarity::Event,
            Relic::FakeStrikeDummy => RelicRarity::Event,
            Relic::FakeVenerableTeaSet => RelicRarity::Event,
            Relic::FencingManual => RelicRarity::Common,
            Relic::FestivePopper => RelicRarity::Common,
            Relic::Fiddle => RelicRarity::Ancient,
            Relic::ForgottenSoul => RelicRarity::Event,
            Relic::FragrantMushroom => RelicRarity::Event,
            Relic::FresnelLens => RelicRarity::Event,
            Relic::FrozenEgg => RelicRarity::Rare,
            Relic::FuneraryMask => RelicRarity::Uncommon,
            Relic::FurCoat => RelicRarity::Ancient,
            Relic::GalacticDust => RelicRarity::Uncommon,
            Relic::GamblingChip => RelicRarity::Rare,
            Relic::GamePiece => RelicRarity::Rare,
            Relic::GhostSeed => RelicRarity::Shop,
            Relic::Girya => RelicRarity::Rare,
            Relic::GlassEye => RelicRarity::Ancient,
            Relic::Glitter => RelicRarity::Ancient,
            Relic::GnarledHammer => RelicRarity::Shop,
            Relic::GoldenCompass => RelicRarity::Ancient,
            Relic::GoldenPearl => RelicRarity::Ancient,
            Relic::GoldPlatedCables => RelicRarity::Uncommon,
            Relic::Gorget => RelicRarity::Common,
            Relic::GremlinHorn => RelicRarity::Uncommon,
            Relic::HandDrill => RelicRarity::Event,
            Relic::HappyFlower => RelicRarity::Common,
            Relic::HelicalDart => RelicRarity::Rare,
            Relic::HistoryCourse => RelicRarity::Event,
            Relic::HornCleat => RelicRarity::Uncommon,
            Relic::IceCream => RelicRarity::Rare,
            Relic::InfusedCore => RelicRarity::Starter,
            Relic::IntimidatingHelmet => RelicRarity::Rare,
            Relic::IronClub => RelicRarity::Ancient,
            Relic::IvoryTile => RelicRarity::Rare,
            Relic::JeweledMask => RelicRarity::Ancient,
            Relic::JewelryBox => RelicRarity::Ancient,
            Relic::JossPaper => RelicRarity::Uncommon,
            Relic::JuzuBracelet => RelicRarity::Common,
            Relic::Kifuda => RelicRarity::Shop,
            Relic::Kunai => RelicRarity::Rare,
            Relic::Kusarigama => RelicRarity::Uncommon,
            Relic::Lantern => RelicRarity::Common,
            Relic::LargeCapsule => RelicRarity::Ancient,
            Relic::LastingCandy => RelicRarity::Rare,
            Relic::LavaLamp => RelicRarity::Shop,
            Relic::LavaRock => RelicRarity::Ancient,
            Relic::LeadPaperweight => RelicRarity::Ancient,
            Relic::LeafyPoultice => RelicRarity::Ancient,
            Relic::LeesWaffle => RelicRarity::Shop,
            Relic::LetterOpener => RelicRarity::Uncommon,
            Relic::LizardTail => RelicRarity::Rare,
            Relic::LoomingFruit => RelicRarity::Ancient,
            Relic::LordsParasol => RelicRarity::Ancient,
            Relic::LostCoffer => RelicRarity::Ancient,
            Relic::LostWisp => RelicRarity::Event,
            Relic::LuckyFysh => RelicRarity::Uncommon,
            Relic::LunarPastry => RelicRarity::Rare,
            Relic::Mango => RelicRarity::Rare,
            Relic::MassiveScroll => RelicRarity::Ancient,
            Relic::MawBank => RelicRarity::Event,
            Relic::MealTicket => RelicRarity::Common,
            Relic::MeatCleaver => RelicRarity::Ancient,
            Relic::MeatOnTheBone => RelicRarity::Rare,
            Relic::MembershipCard => RelicRarity::Shop,
            Relic::MercuryHourglass => RelicRarity::Uncommon,
            Relic::Metronome => RelicRarity::Rare,
            Relic::MiniatureCannon => RelicRarity::Uncommon,
            Relic::MiniatureTent => RelicRarity::Shop,
            Relic::MiniRegent => RelicRarity::Rare,
            Relic::MoltenEgg => RelicRarity::Rare,
            Relic::MrStruggles => RelicRarity::Event,
            Relic::MummifiedHand => RelicRarity::Rare,
            Relic::MusicBox => RelicRarity::Ancient,
            Relic::MysticLighter => RelicRarity::Shop,
            Relic::NeowsTorment => RelicRarity::Ancient,
            Relic::NewLeaf => RelicRarity::Ancient,
            Relic::NinjaScroll => RelicRarity::Shop,
            Relic::Nunchaku => RelicRarity::Uncommon,
            Relic::NutritiousOyster => RelicRarity::Ancient,
            Relic::NutritiousSoup => RelicRarity::Ancient,
            Relic::OddlySmoothStone => RelicRarity::Common,
            Relic::OldCoin => RelicRarity::Rare,
            Relic::OrangeDough => RelicRarity::Rare,
            Relic::Orichalcum => RelicRarity::Uncommon,
            Relic::OrnamentalFan => RelicRarity::Uncommon,
            Relic::Orrery => RelicRarity::Shop,
            Relic::PaelsBlood => RelicRarity::Ancient,
            Relic::PaelsClaw => RelicRarity::Ancient,
            Relic::PaelsEye => RelicRarity::Ancient,
            Relic::PaelsFlesh => RelicRarity::Ancient,
            Relic::PaelsGrowth => RelicRarity::Ancient,
            Relic::PaelsHorn => RelicRarity::Ancient,
            Relic::PaelsLegion => RelicRarity::Ancient,
            Relic::PaelsTears => RelicRarity::Ancient,
            Relic::PaelsTooth => RelicRarity::Ancient,
            Relic::PaelsWing => RelicRarity::Ancient,
            Relic::PandorasBox => RelicRarity::Ancient,
            Relic::Pantograph => RelicRarity::Uncommon,
            Relic::PaperKrane => RelicRarity::Rare,
            Relic::PaperPhrog => RelicRarity::Uncommon,
            Relic::ParryingShield => RelicRarity::Uncommon,
            Relic::Pear => RelicRarity::Uncommon,
            Relic::Pendulum => RelicRarity::Common,
            Relic::PenNib => RelicRarity::Uncommon,
            Relic::Permafrost => RelicRarity::Common,
            Relic::PetrifiedToad => RelicRarity::Uncommon,
            Relic::PhilosophersStone => RelicRarity::Ancient,
            Relic::PhylacteryUnbound => RelicRarity::Starter,
            Relic::Planisphere => RelicRarity::Uncommon,
            Relic::Pocketwatch => RelicRarity::Rare,
            Relic::PollinousCore => RelicRarity::Event,
            Relic::Pomander => RelicRarity::Ancient,
            Relic::PotionBelt => RelicRarity::Common,
            Relic::PowerCell => RelicRarity::Rare,
            Relic::PrayerWheel => RelicRarity::Rare,
            Relic::PrecariousShears => RelicRarity::Ancient,
            Relic::PreciseScissors => RelicRarity::Ancient,
            Relic::PreservedFog => RelicRarity::Ancient,
            Relic::PrismaticGem => RelicRarity::Ancient,
            Relic::PumpkinCandle => RelicRarity::Ancient,
            Relic::PunchDagger => RelicRarity::Shop,
            Relic::RadiantPearl => RelicRarity::Ancient,
            Relic::RainbowRing => RelicRarity::Rare,
            Relic::RazorTooth => RelicRarity::Rare,
            Relic::RedMask => RelicRarity::Uncommon,
            Relic::RedSkull => RelicRarity::Common,
            Relic::Regalite => RelicRarity::Uncommon,
            Relic::RegalPillow => RelicRarity::Common,
            Relic::ReptileTrinket => RelicRarity::Uncommon,
            Relic::RingingTriangle => RelicRarity::Shop,
            Relic::RingOfTheDrake => RelicRarity::Starter,
            Relic::RingOfTheSnake => RelicRarity::Starter,
            Relic::RippleBasin => RelicRarity::Uncommon,
            Relic::RoyalPoison => RelicRarity::Event,
            Relic::RoyalStamp => RelicRarity::Shop,
            Relic::RuinedHelmet => RelicRarity::Rare,
            Relic::RunicCapacitor => RelicRarity::Shop,
            Relic::RunicPyramid => RelicRarity::Ancient,
            Relic::Sai => RelicRarity::Ancient,
            Relic::SandCastle => RelicRarity::Ancient,
            Relic::ScreamingFlagon => RelicRarity::Shop,
            Relic::ScrollBoxes => RelicRarity::Ancient,
            Relic::SeaGlass => RelicRarity::Ancient,
            Relic::SealOfGold => RelicRarity::Ancient,
            Relic::SelfFormingClay => RelicRarity::Uncommon,
            Relic::SereTalon => RelicRarity::Ancient,
            Relic::Shovel => RelicRarity::Rare,
            Relic::Shuriken => RelicRarity::Rare,
            Relic::SignetRing => RelicRarity::Ancient,
            Relic::SilverCrucible => RelicRarity::Ancient,
            Relic::SlingOfCourage => RelicRarity::Shop,
            Relic::SmallCapsule => RelicRarity::Ancient,
            Relic::SneckoEye => RelicRarity::Ancient,
            Relic::SneckoSkull => RelicRarity::Common,
            Relic::Sozu => RelicRarity::Ancient,
            Relic::SparklingRouge => RelicRarity::Uncommon,
            Relic::SpikedGauntlets => RelicRarity::Ancient,
            Relic::StoneCalendar => RelicRarity::Rare,
            Relic::StoneCracker => RelicRarity::Uncommon,
            Relic::StoneHumidifier => RelicRarity::Ancient,
            Relic::Storybook => RelicRarity::Ancient,
            Relic::Strawberry => RelicRarity::Common,
            Relic::StrikeDummy => RelicRarity::Common,
            Relic::SturdyClamp => RelicRarity::Rare,
            Relic::SwordOfJade => RelicRarity::Event,
            Relic::SwordOfStone => RelicRarity::Event,
            Relic::SymbioticVirus => RelicRarity::Uncommon,
            Relic::TanxsWhistle => RelicRarity::Ancient,
            Relic::TeaOfDiscourtesy => RelicRarity::Event,
            Relic::TheAbacus => RelicRarity::Shop,
            Relic::TheBoot => RelicRarity::Event,
            Relic::TheCourier => RelicRarity::Rare,
            Relic::ThrowingAxe => RelicRarity::Ancient,
            Relic::Tingsha => RelicRarity::Uncommon,
            Relic::TinyMailbox => RelicRarity::Common,
            Relic::ToastyMittens => RelicRarity::Ancient,
            Relic::Toolbox => RelicRarity::Shop,
            Relic::TouchOfOrobas => RelicRarity::Ancient,
            Relic::ToughBandages => RelicRarity::Rare,
            Relic::ToxicEgg => RelicRarity::Rare,
            Relic::ToyBox => RelicRarity::Ancient,
            Relic::TriBoomerang => RelicRarity::Ancient,
            Relic::TungstenRod => RelicRarity::Rare,
            Relic::TuningFork => RelicRarity::Uncommon,
            Relic::TwistedFunnel => RelicRarity::Uncommon,
            Relic::UnceasingTop => RelicRarity::Rare,
            Relic::UndyingSigil => RelicRarity::Shop,
            Relic::UnsettlingLamp => RelicRarity::Rare,
            Relic::Vajra => RelicRarity::Common,
            Relic::Vambrace => RelicRarity::Uncommon,
            Relic::VelvetChoker => RelicRarity::Ancient,
            Relic::VenerableTeaSet => RelicRarity::Common,
            Relic::VeryHotCocoa => RelicRarity::Ancient,
            Relic::VexingPuzzlebox => RelicRarity::Rare,
            Relic::VitruvianMinion => RelicRarity::Shop,
            Relic::WarHammer => RelicRarity::Ancient,
            Relic::WarPaint => RelicRarity::Common,
            Relic::Whetstone => RelicRarity::Common,
            Relic::WhisperingEarring => RelicRarity::Ancient,
            Relic::WhiteBeastStatue => RelicRarity::Rare,
            Relic::WhiteStar => RelicRarity::Rare,
            Relic::WingCharm => RelicRarity::Shop,
            Relic::WongoCustomerAppreciationBadge => RelicRarity::Event,
            Relic::WongosMysteryTicket => RelicRarity::Event,
            Relic::YummyCookie => RelicRarity::Ancient,
        }
    }
}
