use std::sync::atomic::{AtomicI32, Ordering};
use std::sync::mpsc;
use crate::dotnet::random::DotNetRandom;
use crate::events::event::EventOption;
use crate::GameState;

type HashCode = i32;

pub fn generate_random_seed(rng: &mut DotNetRandom) -> String {
    const CHARS: &[u8] = b"ABCDEFGHIJKMNPQRSTUVWXYZ0123456789";
    const LEN: usize = 10;
    let mut buf = [0u8; LEN];

    for b in buf.iter_mut() {
        *b = CHARS[rng.next_range(0, CHARS.len() as i32) as usize];
    }

    unsafe { String::from_utf8_unchecked(buf.to_vec()) }
}

/// A condition on the derived hash code of a seed.
type HashCondition = Box<dyn Fn(HashCode) -> bool + Send + Sync>;

/// A condition on the options generated by an event for a given seed.
/// Returns true if the options satisfy the condition.
type EventCondition = Box<dyn Fn(&[EventOption]) -> bool + Send + Sync>;

/// Describes how to construct and evaluate an event from a GameState.
struct EventEntry {
    /// Builds the event options from a game state
    #[allow(clippy::type_complexity)]
    build: Box<dyn Fn(&GameState) -> Vec<EventOption> + Send + Sync>,
    /// All conditions that must pass on the generated options
    conditions: Vec<EventCondition>,
}

pub struct SeedCracker {
    hash_conditions: Vec<HashCondition>,
    event_entries: Vec<EventEntry>,
    game_state: GameState,

    pub attempts: AtomicI32,
}

impl SeedCracker {
    pub fn with_game_state(game_state: GameState) -> Self {
        Self {
            hash_conditions: vec![],
            event_entries: vec![],
            game_state,

            attempts: AtomicI32::default()
        }
    }

    /// Add a condition on the numeric hash of the seed.
    pub fn add_condition(mut self, condition: impl Fn(HashCode) -> bool + Send + Sync + 'static) -> Self {
        self.hash_conditions.push(Box::new(condition));
        self
    }

    /// Register an event to search over. `build` constructs the event options from a GameState.
    /// Chain `.with_event_condition()` calls after this to add conditions on the options.
    pub fn add_event(
        mut self,
        build: impl Fn(&GameState) -> Vec<EventOption> + Send + Sync + 'static,
    ) -> Self {
        self.event_entries.push(EventEntry {
            build: Box::new(build),
            conditions: Vec::new(),
        });
        self
    }

    /// Add a condition on the most recently registered event's options.
    /// Matches by value — use the closure to inspect option contents freely.
    pub fn with_event_condition(
        mut self,
        condition: impl Fn(&[EventOption]) -> bool + Send + Sync + 'static,
    ) -> Self {
        self.event_entries
            .last_mut()
            .expect("call add_event() before with_event_condition()")
            .conditions
            .push(Box::new(condition));
        self
    }

    /// Convenience: match if any option satisfies a per-option predicate.
    pub fn with_any_option(
        self,
        predicate: impl Fn(&EventOption) -> bool + Send + Sync + 'static,
    ) -> Self {
        self.with_event_condition(move |opts| opts.iter().any(&predicate))
    }

    /// Convenience: match if all options satisfy a per-option predicate.
    pub fn with_all_options(
        self,
        predicate: impl Fn(&EventOption) -> bool + Send + Sync + 'static,
    ) -> Self {
        self.with_event_condition(move |opts| opts.iter().all(&predicate))
    }

    #[allow(clippy::field_reassign_with_default)]
    fn test_seed(&self, seed: &str) -> bool {
        let derived = crate::helpers::string_helper::get_deterministic_hash_code(seed);

        if !self.hash_conditions.iter().all(|c| c(derived)) {
            return false;
        }

        let mut game_state = self.game_state.clone(); // todo: slooow
        game_state.numeric_seed = derived;

        for entry in &self.event_entries {
            let options = (entry.build)(&game_state);
            if !entry.conditions.iter().all(|c| c(&options)) {
                return false;
            }
        }

        true
    }

    pub fn crack(&self) -> String {
        let (tx, rx) = mpsc::channel();

        rayon::scope(|s| {
            for i in 0..rayon::current_num_threads() {
                let tx = tx.clone();
                let mut rng = DotNetRandom::new(i as i32);
                s.spawn(move |_| loop {
                    if tx.is_disconnected() {
                        break;
                    }

                    self.attempts.fetch_add(1, Ordering::Relaxed);

                    let seed = generate_random_seed(&mut rng);
                    if self.test_seed(&seed) {
                        let _ = tx.send(seed);
                        break;
                    }
                });
            }
        });

        rx.recv().unwrap()
    }
}